- platform: mqtt
  name: "Bureau"
  availability_topic: "/sonoff/tele/bureau/store/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  position_topic: "/sonoff/stat/bureau/store/SHUTTER1"
  position_open: 0
  position_closed: 100
  set_position_topic: "/sonoff/cmnd/bureau/store/ShutterPosition1"
  command_topic: "/sonoff/cmnd/bureau/store/Backlog"
  payload_open: "ShutterOpen1"
  payload_close: "ShutterClose1"
  payload_stop: "ShutterStop1"
  retain: false
  optimistic: false
  qos: 1
- platform: mqtt
  name: "Chambre"
  availability_topic: "/sonoff/tele/chambre/store/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  position_topic: "/sonoff/stat/chambre/store/SHUTTER1"
  set_position_topic: "/sonoff/cmnd/chambre/store/ShutterPosition1"
  command_topic: "/sonoff/cmnd/chambre/store/Backlog"
  position_open: 0
  position_closed: 100
  payload_open: "ShutterOpen1"
  payload_close: "ShutterClose1"
  payload_stop: "ShutterStop1"
  retain: false
  optimistic: false
  qos: 1
